### PR TITLE
Add proc macros (continued from #6)

### PR DESCRIPTION
**Pull request by de-vri-es**
This PR continues on top of #6.

Changes compared to #6:
  * Use `git rev-parse --git-dir` to find the git directory.
  * Use `syn` to parse macro arguments with pretty errors.
  * Move the actual implementation to a third crate and call into it from the macro crate and the main crate.

Feedback welcome.

### CODE REVIEW

**Comment by de-vri-es** [comment]
Still to do:
* Update the documentation
* Maybe deprecate or remove the functions that instruct cargo to put the version in the environment. People could just use the proc macro in their code and have a build script that always triggers a rebuild if they want the old behaviour.

**Comment by droundy** [comment]
It looks good to me at a quick reading!

**Comment by de-vri-es** [comment]
Merged! :tada:

**Comment by droundy** [comment]
Yay!

**Pull request merged**
