### PR TITLE
Add the `set_env_with_name` function for env with custom name

### PR DESCRIPTION
**Pull request by TeXitoi**

### CODE REVIEW

**Comment by m-ou-se** [comment]
Thanks!

**Comment by TeXitoi** [comment]
That was fast!

**Comment by m-ou-se** [comment]
The new version is now published to crates.io.

**Comment by TeXitoi** [comment]
Thanks for this fast reaction. Will use it in https://github.com/CanalTP/mimirsbrunn

FYI, you didn't need to update to "0.2", "0.1.3" was OK as there is no incompatibilities.

**Pull request merged**
